name: publish agents-bundle
on:
  workflow_call:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'
      tag:
        required: false
        type: string
        default: 'latest'
        description: 'tag to publish under, default: latest'

  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'
      tag:
        required: false
        type: string
        default: 'latest'
        description: 'tag to publish under, default: latest'

jobs:
  call-release-workflow:
    if: ${{ inputs.branch }}
    uses: forcedotcom/bundle-publish-scripts/.github/workflows/releaseWithCoreBundle.yml@main
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      tag: ${{ inputs.tag }}
